### PR TITLE
Feature: add X emoji on created ticket, close with emoji

### PR DESCRIPTION
**Pull request by dunak-debug**
**Versioning information**

- [ ] This includes major changes (breaking changes)
- [X] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes)
- [ ] This does not change functionality at all (code refactoring, comments)

**Is this related to an issue?**

**Changes made**

_messageReactionAdd.js (listeners)_
`} else if(r.emoji.name === '❌') {
    await this.client.tickets.close(channel.id, member.user.id, guild.id);
}`

_manager.js (onCreate - ticket)_
`await sent.react('❌')`

**Confirmations**

- [ ] I have updated related documentation (if necessary)
- [ ] My changes use consistent code style
- [ ] My changes have been tested and confirmed to work

### CODE REVIEW

**Comment by eartharoid** [comment]
Personally, I don't see the benefit of this addition. Isn't it more effort to scroll up to the first message (or click on pinned messages and jump to the first message) than to simply type or paste `-close`?

If this is added it needs to be optional (configured in guild settings) and there needs to be the same confirmation as the close command. Currently, this immediately deletes the channel with no warning.

**Comment by dunak-debug** [comment]
no need to be merged, just to show off based on some people feature requests ;) you can close that

**Comment by PuneetGopinath** [comment]
> Personally, I don't see the benefit of this addition. Isn't it more effort to scroll up to the first message (or click on pinned messages and jump to the first message) than to simply type or paste `-close`?
> 
> If this is added it needs to be optional (configured in guild settings) and there needs to be the same confirmation as the close command. Currently, this immediately deletes the channel with no warning.

But this is good. I saw this is many other ticket systems.

**Comment by dunak-debug** [comment]
if you agree i can look onto it and make it optional in category configuration, for now i don´t have idea how to trigger confirmation dialog without duplicating code because it is contained in command

**Comment by eartharoid** [comment]
As reactions are being replaced with buttons it would be a waste of time to add this right now; any code added would need to be rewritten in a few days. We can come back to it later.

**Comment by eartharoid** [comment]
v3.1 introduced a close button option.

**Pull request closed without merging**
