### PR TITLE
refactor: use djs v13

### PR DESCRIPTION
**Pull request by PuneetGopinath**
**Versioning information**

- [ ] This includes major changes (breaking changes)
- [x] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes)
- [ ] This does not change functionality at all (code refactoring, comments)

**Is this related to an issue?**

**Changes made**

Updating to v13

**Confirmations**

- [ ] I have updated related documentation (if necessary)
- [ ] My changes use consistent code style
- [ ] My changes have been tested and confirmed to work

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@eartharoid I currently don't have access to my pc. I have done all this in phone. When I get my pc tomorrow. I will test and run npm install to update package-lock

**Comment by eartharoid** [comment]
I started working on it minutes before you opened this PR so I have already [updated the dependencies](https://github.com/discord-tickets/bot/commit/36ad172d23ed5a8520a52c7a45e0004e2e0c4d11). Thanks for helping with updating commands etc.

**Comment by PuneetGopinath** [comment]
> I started working on it minutes before you opened this PR so I have already [updated the dependencies](https://github.com/discord-tickets/bot/commit/36ad172d23ed5a8520a52c7a45e0004e2e0c4d11). Thanks for helping with updating commands etc.

Welcome. I already received a email when you had put me as a commit co author

**Comment by eartharoid** [comment]
> Welcome. I already received a email when you had put me as a commit co author

Well, I attempted to but I don't know if it worked because I used your username instead of email.

**Comment by PuneetGopinath** [comment]
> Well, I attempted to but I don't know if it worked because I used your username instead of email.

I wouldn't have received an email If it didn't work, so it worked

**Comment by PuneetGopinath** [comment]
Now I somehow got it cloned to my phone

**Comment by PuneetGopinath** [comment]
@eartharoid Why do you need direct messages intent?

**Comment by PuneetGopinath** [comment]
I decided to test now itself by hosting on a hosting provider. Testing from patch-2 branch in my fork

**Comment by eartharoid** [comment]
>  @eartharoid Why do you need direct messages intent?

Good question. I was thinking about the message you get [when you DM the bot](https://github.com/discord-tickets/bot/blob/v2.1.3/src/events/message.js#L20), but that is only in v2, not v3.

**Comment by PuneetGopinath** [comment]
@eartharoid what's this:
```js
TypeError: Cannot read property 'db' of undefined
    at Guild.getSettings (/usr/src/app/src/structures/guild.js:9:40)
    at MessageEventListener.execute (/usr/src/app/src/listeners/message.js:14:40)
    at Bot.<anonymous> (/usr/src/app/src/modules/listeners/loader.js:27:64)
    at Bot.emit (node:events:394:28)
    at MessageCreateAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:18)
    at Object.module.exports [as MESSAGE_CREATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:132:16)
```

**Comment by PuneetGopinath** [comment]
Understood the problem

**Comment by PuneetGopinath** [comment]
@eartharoid Can you help me? Can't fix it

**Comment by PuneetGopinath** [comment]
Just now checked your discord presence, you already started editing

**Comment by eartharoid** [comment]
`this` doesn't refer to the `Guild` anymore, so `this.client` does not exist. I'm currently completely removing the structures system and replacing with simple util functions.

**Review by eartharoid — APPROVED** [review]
@all-contributors please add @PuneetGopinath for code

**Comment by eartharoid** [comment]
@all-contributors please add @PuneetGopinath for code

**Pull request merged**
