### PR TITLE
Create .env

### PR DESCRIPTION
**Pull request by Awsomegameplay123**
**Versioning information**

- [ ] This includes major changes (breaking changes)
- [ ] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes)
- [ ] This does not change functionality at all (code refactoring, comments)

**Is this related to an issue?**

**Changes made**

**Confirmations**

- [ ] I have updated related documentation (if necessary)
- [ ] My changes use consistent code style
- [ ] My changes have been tested and confirmed to work

### CODE REVIEW

**Comment by itzJOHv** [comment]
😂

**Comment by eartharoid** [comment]
@Awsomegameplay123 reset your Discord token if you haven't already.

**Comment by RooRay** [comment]
> @Awsomegameplay123 reset your Discord token if you haven't already.

Do this, you leaked it in the commit, generally never put .env files on GitHub unless you’re 1000% sure they’re blank, also DT generates the .env for you

**Comment by itzJOHv** [comment]
@eartharoid @RooRay Discord automatically regenerates tokens that are in public repos

**Pull request closed without merging**
