### PR TITLE
refactor(panel): switch to buttons

### PR DESCRIPTION
**Pull request by PuneetGopinath**
**Versioning information**

- [ ] This includes major changes (breaking changes)
- [x] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes)
- [ ] This does not change functionality at all (code refactoring, comments)

**Is this related to an issue?**

**Changes made**

Used buttons instead of emojis

**Confirmations**

- [ ] I have updated related documentation (if necessary)
- [x] My changes use consistent code style
- [ ] My changes have been tested and confirmed to work

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
I dunno what's this: https://github.com/PuneetGopinath/tickets-bot/blob/patch-3/src/commands/panel.js#L212
So I left it without changing anything

**Comment by thevisuales** [comment]
Good job! I am looking forward to implementing this soon.

**Comment by PuneetGopinath** [comment]
> Good job! I am looking forward to implementing this soon.

Oh thanks. @eartharoid isn't co operating with me, so I left this pr.

**Comment by thevisuales** [comment]
Does that mean you're stuck with something? Sorry not to be helpful, my intention is to familiarize myself with the code for this project in a few days and try to get it up and running in my community. If you can get the buttons to work let me know

**Comment by PuneetGopinath** [comment]
> Does that mean you're stuck with something? Sorry not to be helpful, my intention is to familiarize myself with the code for this project in a few days and try to get it up and running in my community. If you can get the buttons to work let me know

> Does that mean you're stuck with something?

Yeah. I can't create a panel to test the buttons

**Comment by thevisuales** [comment]
Update: I have managed to open tickets using buttons. I have also managed to claim the ticket. I am missing the ticket removal process to implement.

**Comment by thevisuales** [comment]
PuneetGopinath , I need you to give me write permission to be able to merge my changes.

**Comment by PuneetGopinath** [comment]
> PuneetGopinath , I need you to give me write permission to be able to merge my changes.

Done

**Comment by PuneetGopinath** [comment]
@all-contributors Add @thevisuales for code

**Comment by eartharoid** [comment]
Due to the state of this PR I have done it myself in https://github.com/discord-tickets/bot/commit/c3a1db5dd88157bef49eff43ad08108a33f3d53b and https://github.com/discord-tickets/bot/commit/92aa32c9411e6912231e6af6e69649bb008883b3 but I have added you both as co-authors so you should be recognised as contributors on GitHub.

**Pull request closed without merging**
